package controller;


import java.io.IOException;
import java.io.PrintWriter;
import java.sql.*;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/db-test")
public class SimpleTestController extends HttpServlet {
    
    // Oracle Database settings
    private static final String DB_URL = "jdbc:oracle:thin:@localhost:1521/ORCLPDB";
    private static final String DB_USER = "itemSys";
    private static final String DB_PASSWORD = "1234";
    
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) 
            throws ServletException, IOException {
        
        System.out.println("🧪 SimpleTestController called!");
        
        resp.setContentType("text/html;charset=UTF-8");
        PrintWriter out = resp.getWriter();
        
        out.println("<!DOCTYPE html>");
        out.println("<html><head><title>Database Test</title></head><body>");
        out.println("<h1>📊 Database Connection Test</h1>");
        
        // Test 1: Try to load Oracle driver
        out.println("<h2>1. Driver Test:</h2>");
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            out.println("<p style='color: green;'>✅ Oracle JDBC Driver loaded successfully!</p>");
            System.out.println("✅ Oracle driver loaded");
        } catch (ClassNotFoundException e) {
            out.println("<p style='color: red;'>❌ Oracle JDBC Driver not found: " + e.getMessage() + "</p>");
            System.err.println("❌ Driver not found: " + e.getMessage());
            out.println("</body></html>");
            return;
        }
        
        // Test 2: Try to connect to database
        out.println("<h2>2. Connection Test:</h2>");
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
            out.println("<p style='color: green;'>✅ Database connection successful!</p>");
            System.out.println("✅ Database connected");
            
            // Get database info
            DatabaseMetaData metaData = conn.getMetaData();
            out.println("<p><strong>Database:</strong> " + metaData.getDatabaseProductName() + "</p>");
            out.println("<p><strong>Version:</strong> " + metaData.getDatabaseProductVersion() + "</p>");
            
        } catch (SQLException e) {
            out.println("<p style='color: red;'>❌ Connection failed: " + e.getMessage() + "</p>");
            out.println("<p><strong>SQL State:</strong> " + e.getSQLState() + "</p>");
            out.println("<p><strong>Error Code:</strong> " + e.getErrorCode() + "</p>");
            System.err.println("❌ Connection failed: " + e.getMessage());
            out.println("</body></html>");
            return;
        }
        
        // Test 3: Try different table name variations
        out.println("<h2>3. Table Test:</h2>");
        String[] tableQueries = {
            "SELECT COUNT(*) FROM items",
            "SELECT COUNT(*) FROM itemSys.items", 
            "SELECT COUNT(*) FROM ITEMS",
            "SELECT COUNT(*) FROM ITEMSYS.ITEMS"
        };
        
        boolean tableFound = false;
        String workingQuery = null;
        
        for (String query : tableQueries) {
            try (Statement stmt = conn.createStatement();
                 ResultSet rs = stmt.executeQuery(query)) {
                
                if (rs.next()) {
                    int count = rs.getInt(1);
                    out.println("<p style='color: green;'>✅ Query: <code>" + query + "</code> → Count: " + count + "</p>");
                    System.out.println("✅ " + query + " → " + count + " rows");
                    tableFound = true;
                    workingQuery = query.replace("COUNT(*)", "*");
                    break;
                }
                
            } catch (SQLException e) {
                out.println("<p style='color: orange;'>⚠️ Query failed: <code>" + query + "</code> → " + e.getMessage() + "</p>");
                System.out.println("⚠️ " + query + " failed: " + e.getMessage());
            }
        }
        
        if (!tableFound) {
            out.println("<p style='color: red;'>❌ No accessible 'items' table found!</p>");
            out.println("<h3>💡 Try creating the table:</h3>");
            out.println("<pre>");
            out.println("CREATE TABLE items (");
            out.println("    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,");
            out.println("    name VARCHAR2(100) NOT NULL,");
            out.println("    price NUMBER(10,2) NOT NULL,");
            out.println("    quantity NUMBER DEFAULT 0");
            out.println(");");
            out.println("");
            out.println("INSERT INTO items (name, price, quantity) VALUES ('Laptop', 15000, 10);");
            out.println("INSERT INTO items (name, price, quantity) VALUES ('Mouse', 200, 50);");
            out.println("INSERT INTO items (name, price, quantity) VALUES ('Keyboard', 500, 20);");
            out.println("</pre>");
            out.println("</body></html>");
            return;
        }
        
        // Test 4: Show actual data
        out.println("<h2>4. Data Test:</h2>");
        try (Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(workingQuery + " WHERE ROWNUM <= 5")) {
            
            out.println("<table border='1' cellpadding='5'>");
            out.println("<tr><th>ID</th><th>Name</th><th>Price</th><th>Quantity</th></tr>");
            
            int rowCount = 0;
            while (rs.next()) {
                out.println("<tr>");
                out.println("<td>" + rs.getInt("id") + "</td>");
                out.println("<td>" + rs.getString("name") + "</td>");
                out.println("<td>" + rs.getDouble("price") + "</td>");
                out.println("<td>" + rs.getInt("quantity") + "</td>");
                out.println("</tr>");
                rowCount++;
                
                System.out.println("📋 Row: " + rs.getInt("id") + ", " + 
                                 rs.getString("name") + ", " + 
                                 rs.getDouble("price") + ", " + 
                                 rs.getInt("quantity"));
            }
            out.println("</table>");
            
            if (rowCount == 0) {
                out.println("<p style='color: orange;'>⚠️ Table exists but no data found!</p>");
            } else {
                out.println("<p style='color: green;'>✅ Found " + rowCount + " records!</p>");
            }
            
        } catch (SQLException e) {
            out.println("<p style='color: red;'>❌ Data query failed: " + e.getMessage() + "</p>");
            System.err.println("❌ Data query failed: " + e.getMessage());
        } finally {
            try {
                if (conn != null) conn.close();
            } catch (SQLException e) {
                System.err.println("❌ Error closing connection: " + e.getMessage());
            }
        }
        
        out.println("<hr>");
        out.println("<p><a href='test'>← Back to Test Servlet</a></p>");
        out.println("<p><a href='items'>→ Try Items Controller</a></p>");
        out.println("</body></html>");
        
        out.flush();
        out.close();
    }
}