CREATE TABLE itemSys.items (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    price NUMBER(10,2) NOT NULL,
    quantity NUMBER DEFAULT 0
);


INSERT INTO itemSys.items (name, price, quantity) VALUES ('Laptop', 15000, 10);
INSERT INTO itemSys.items (name, price, quantity) VALUES ('Mouse', 200, 50);
INSERT INTO itemSys.items (name, price, quantity) VALUES ('Keyboard', 500, 20);


SELECT * FROM itemSys.items;
